-- O arquivo portal_informativo.sql guarda o script do banco de dados Portal Informativo,
-- exportado de PHPMyAdmin

-- O banco possui as seguintes tabelas: 
--   01. professores
--   02. materias
--   03. professor_materia
--   04. cursos
--   05. curso_materia
--   06. turmas
--   07. curso_turma
--   08. alunos
--   09. informativos
--   10. turma_informativo
--   11. dados_eventos
--   12. dados_avaliacoes
--   13. dados_materiais
--   14. arquivos
--   15. informativo_arquivo