lista_alunos = [ 
    {
        "nome":"Adriely Daiany",
        "matricula":"20231144010036",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info36",
        "status":"aluno",
    },
    {
        "nome":"Afonso Silva",
        "matricula":"20231144010009",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info09",
        "status":"aluno",
    },
    {
        "nome":"Alicia Martins",
        "matricula":"20231144010066",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info66",
        "status":"aluno",
    },
    {
        "nome":"Amilton de Almeida",
        "matricula":"20231144010030",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info30",
        "status":"aluno",
    },
    {
        "nome":"Ananda Beatriz",
        "matricula":"20231144010063",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info63",
        "status":"aluno",
    },
    {
        "nome":"Antony Gabriel",
        "matricula":"20231144010052",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info52",
        "status":"aluno",
    },    
    {
        "nome":"Breno Gusmão",
        "matricula":"20231144010022",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info22",
        "status":"aluno",
    },
    {
        "nome":"Bruno Gustavo",
        "matricula":"20231144010008",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info08",
        "status":"aluno",
    },    
    {
        "nome":"Cauã de Lima",
        "matricula":"20231144010003",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info03",
        "status":"aluno",
    },
    {
        "nome":"Davi Galdino",
        "matricula":"20231144010032",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info32",
        "status":"aluno",
    },   
    {
        "nome":"Edvan Coelho",
        "matricula":"20231144010021",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info21",
        "status":"aluno",
    },
    {
        "nome":"Fabiana Antunes",
        "matricula":"20231144010062",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info62",
        "status":"aluno",
    },
    {
        "nome":"Geovana Gabriele",
        "matricula":"20231144010080",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info80",
        "status":"aluno",
    },
    {
        "nome":"Guilherme Narciso",
        "matricula":"20231144010023",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info23",
        "status":"aluno",
    },
    {
        "nome":"Harlley Rocha",
        "matricula":"20231144010051",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info51",
        "status":"aluno",
    },
    {
        "nome":"Ingrid Beatriz",
        "matricula":"20231144010041",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info41",
        "status":"aluno",
    },
    {
        "nome":"Isadora Fernandes",
        "matricula":"20231144010025",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info25",
        "status":"aluno",
    },
    {
        "nome":"Jadson Lima",
        "matricula":"20231144010075",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info75",
        "status":"aluno",
    },
    {
        "nome":"Julia Bezerra",
        "matricula":"20231144010055",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info55",
        "status":"aluno",
    },
    {
        "nome":"Júlio Cesar",
        "matricula":"20231144010043",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info43",
        "status":"aluno-lider",
    },
    {
        "nome":"Ketlyn Kauany",
        "matricula":"20231144010081",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info81",
        "status":"aluno",
    },
    {
        "nome":"Lucas de Lima",
        "matricula":"20231144010027",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info27",
        "status":"aluno",
    },
    {
        "nome":"Maria Gabriella",
        "matricula":"20231144010015",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info15",
        "status":"aluno",
    },
    {
        "nome":"Maria Luisa",
        "matricula":"20231144010067",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info67",
        "status":"aluno",
    },
    {
        "nome":"Mariana Gabrielly",
        "matricula":"20231144010029",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info29",
        "status":"aluno",
    },  
    {
        "nome":"Marina Ribeiro",
        "matricula":"20231144010040",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info40",
        "status":"aluno",
    },
    {
        "nome":"Matheus da Silva",
        "matricula":"20231144010001",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info01",
        "status":"aluno",
    },  
    {
        "nome":"Mikelly da Silva",
        "matricula":"20231144010069",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info69",
        "status":"aluno",
    },
    {
        "nome":"Radmila de Souza",
        "matricula":"20231144010031",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info31",
        "status":"aluno",
    },  
    {
        "nome":"Ramon Lincon",
        "matricula":"20231144010020",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info20",
        "status":"aluno",
    },
    {
        "nome":"Vinícius Alves",
        "matricula":"20231144010007",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info07",
        "status":"aluno",
    },  
    {
        "nome":"Vinícius Costa",
        "matricula":"20231144010054",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info54",
        "status":"aluno",
    },
    {
        "nome":"Vitória da Silva",
        "matricula":"20221144010080",
        "nomeTurma":"info3v", "ID_turma": 1,
        "senha":"info80",
        "status":"aluno",
    },     
]